### ISSUE TITLE
Selection of initial value

### ISSUE THREAD

**Issue by hippyau** [gtgalone/prompt_dialog#11]
Hi, love your widget!

How to select all text of initial value show on display of the prompt, so user erases initial value as soon as entering a character?

Instead of ...
![image](https://user-images.githubusercontent.com/36442309/133276297-92349406-924e-46ac-9cda-7ba1b72870f4.png)

All initial input selected like ...

![image](https://user-images.githubusercontent.com/36442309/133276480-1338c3ae-089c-4a3a-a118-b6bae8b3bce8.png)

Cheers,

**Comment by gtgalone** [comment]
@hippyau Thank you for using!

I have just published with your request.

Please use 1.0.6 version

default value of `isSelectedInitialValue` is true.

So you don't need to it set except you want it unselected.

**Comment by hippyau** [comment]
awesome!  thank you, works great :)
