### ISSUE TITLE
Exception from basic example

### ISSUE THREAD

**Issue by mjablecnik** [gtgalone/prompt_dialog#14]
Hello, when I am trying you basic example so it throw me this error (after click on the button):
![image](https://user-images.githubusercontent.com/2686906/147694339-befecea4-1138-42ef-b8fd-05e7df36d5c2.png)

You should probably update it for latest Flutter version.

**Comment by gtgalone** [comment]
@mjablecnik Thank you for adding this issue!

I have updated about this :)
