### ISSUE TITLE
"isSelectedInitialValue" is never used

### ISSUE THREAD

**Issue by mitrakov** [gtgalone/prompt_dialog#19]
Please add the folloing code to `initState()` to make this field beneficial:
```dart
if (widget.isSelectedInitialValue) {
  controller.selection = TextSelection(baseOffset: 0, extentOffset: value?.length ?? 0);
}
```

**Comment by gtgalone** [comment]
Thank you so much @mitrakov !

I have added controller property.

So you can add your custom controller.

Please use v1.0.10
