### ISSUE TITLE
TextEditingController is not properly disposed

### ISSUE THREAD

**Issue by TechAurelianMisc2** [gtgalone/prompt_dialog#24]
When the user does not specify a custom `TextEditingController` using the `controller` parameter, a `TextEditingController` instance is created automatically in the [`__PromptDialogState.initState`](https://github.com/gtgalone/prompt_dialog/blob/main/lib/prompt_dialog.dart#L180C8-L180C17) method:

```dart
    controller =
        widget.controller ?? TextEditingController(text: widget.initialValue);
```

but it is not properly disposed of, as per the [official documentation](https://api.flutter.dev/flutter/widgets/TextEditingController-class.html):

> Remember to [dispose](https://api.flutter.dev/flutter/foundation/ChangeNotifier/dispose.html) of the [TextEditingController](https://api.flutter.dev/flutter/widgets/TextEditingController-class.html) when it is no longer needed. This will ensure we discard any resources used by the object.

**Comment by gtgalone** [comment]
Thanks @TechAurelian2 !

Please update your version to 1.0.17.
