### ISSUE TITLE
Set to autofocus: true by default

### ISSUE THREAD

**Issue by atn832** [gtgalone/prompt_dialog#5]
Thanks for implementing the autofocus option! It'd be even more useful if it was set to true by default, since most users will want to type right away, instead of tapping the text box.

**Comment by gtgalone** [comment]
@atn832 Yes, That is good idea.

Feel free to make a pull request.

**Comment by gtgalone** [comment]
@atn832 I have released for this issue, please update to 1.0.1

**Comment by atn832** [comment]
Beautiful, thank you!
