### ISSUE TITLE
Press Enter returns the value

### ISSUE THREAD

**Issue by atn832** [gtgalone/prompt_dialog#6]
In the Javascript prompt, pressing Enter will return the value. In this project, pressing Enter will unfocus the textbox.

For now, the workaround is to press Tab, Tab, Enter.

Btw, this is not urgent. I'm posting this to keep track of the issue.

**Comment by gtgalone** [comment]
@atn832 Thank you for this!

I have published with 1.0.2 for this issue :)

**Comment by atn832** [comment]
I forgot to answer back then, but thanks for implementing it so fast. It works well!
