### ISSUE TITLE
initialValue not returned unless textchange

### ISSUE THREAD

**Issue by gnilron** [gtgalone/prompt_dialog#8]
When setting initialValue to something and then using the prompt without editing that initialValue, pressing ok will return null unless you do some typing.

I think having a value as null but an initialValue set this prompt should return initialValue "onOK"

**Comment by gnilron** [comment]
Like on row 66
instead of 
            onPressed: () => Navigator.pop(context, value),
do
            onPressed: () => Navigator.pop(context, (value==null && initialValue!=null)  initialValue : value),

**Comment by gtgalone** [comment]
@gnilron Awesome! Thank you so much.

I have just published 1.0.3 with your code.

Please use new release.
